/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    copy: typeof import('./components/modals/ModalRegisterPlayer copy.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ModalEditPlayer: typeof import('./components/modals/ModalEditPlayer.vue')['default']
    ModalRegisterPlayer: typeof import('./components/modals/ModalRegisterPlayer.vue')['default']
    RegistroDoJogador: typeof import('./components/modals/registro-do-jogador.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
